services:
  postgres:
    image: postgres:14-alpine
    ports:
    - 5434:5432
    environment:
      POSTGRES_DB: "honkai-star-rail"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      